AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Deploys the Web-App bucket

Parameters:
  Environment:
    Type: String
    Default: 'dev'
    Description: Environment for Web-App
    AllowedValues:
      - dev
      - prod

Resources:
  WebAppS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::AccountId}-web-app-bucket-${Environment}
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      AccelerateConfiguration:
        AccelerationStatus: Enabled

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebAppS3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: RequireSSL
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource: !Sub "arn:aws:s3:::${AWS::AccountId}-web-app-bucket-${Environment}/*"
            Condition:
              Bool:
                aws:SecureTransport: false
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
